version: '3.9'

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: registry.digitalocean.com/finpro/sentiment-analysis:latest
    ports:
      - "5001:5001"
    volumes:
      - './functions.py:/app/functions.py'
      - './model:/app/model'
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - BUCKET_NAME=model
      - MODEL_FILENAME=finbert_individual2_sentiment_model.tar.gz
    depends_on:
      - minio

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: registry.digitalocean.com/finpro/sentiment-frontend:latest
    ports:
      - "5000:5000"
    depends_on:
      - api-service

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001" # Expose the MinIO console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: minio server /data
    volumes:
      - minio-data:/data

  minio-client:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (mc alias set myminio http://minio:9000 minioadmin minioadmin); do echo 'Waiting for MinIO...'; sleep 2; done &&
      mc mb -p myminio/model || true &&
      mc cp /data/finbert_individual2_sentiment_model.tar.gz myminio/model/ || echo 'Model already uploaded';
      "

volumes:
  minio-data:
