version: '3.9'

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: registry.digitalocean.com/finpro/sentiment-analysis:latest
    ports:
      - "5001:5001"
    volumes:
      - './functions.py:/app/functions.py'
      - '/opt/models/finbert_individual2_sentiment_model:/app/model'
    environment:
      - MODEL_FILENAME=finbert_individual2_sentiment_model

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: registry.digitalocean.com/finpro/sentiment-frontend:latest
    ports:
      - "5000:5000"
    depends_on:
      - api-service
