FROM python:3.9-slim

WORKDIR /app

COPY functions.py /app/
COPY templates /app/templates/
COPY model/finbert_individual2_sentiment_model /app/model/

RUN apt-get update && apt-get install -y \
    libpq-dev build-essential curl \
    && pip install --no-cache-dir \
    torch transformers nltk newspaper3k flask gunicorn boto3

RUN python -m nltk.downloader stopwords punkt wordnet

EXPOSE 5001

CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5001", "functions:app"]
