name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: "registry.digitalocean.com/finpro"
  IMAGE_NAME: "sentiment-analysis"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Create Override for Dynamic Tagging
      run: |
        echo "version: '3.9'
        services:
          api-service:
            image: $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7}" > docker-compose.override.yaml

    - name: Build Docker Images
      run: docker-compose -f docker-compose.yaml -f docker-compose.override.yaml build

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry
      run: doctl registry login --expiry-seconds 600

    - name: Push Image to DigitalOcean Registry
      run: docker push $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7}

  deploy:
    runs-on: ubuntu-latest
    #needs: build_and_push

    steps:
    - name: Add Remote Host to Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.DIGITALOCEAN_HOST }} >> ~/.ssh/known_hosts
      shell: bash

    - name: Deploy to DigitalOcean Droplet
      env:
        SSH_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        SSH_USERNAME: ${{ secrets.DIGITALOCEAN_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: |
        # Add the remote host to known hosts
        mkdir -p ~/.ssh
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

        # Create the private key file
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        echo "Transferring files to remote server..."
        rsync -avz -e "ssh -i private_key.pem" . $SSH_USERNAME@$SSH_HOST:~/sentiment-analysis/

        echo "Deploying application on the server..."
        ssh -i private_key.pem $SSH_USERNAME@$SSH_HOST << 'EOF'
          echo "Logging into DigitalOcean Container Registry..."
          echo "$DIGITALOCEAN_ACCESS_TOKEN" | docker login registry.digitalocean.com -u $SSH_USERNAME --password-stdin

          echo "Stopping and removing old container..."
          docker stop sentiment-analysis || true
          docker rm sentiment-analysis || true

          echo "Pulling the latest image..."
          docker pull registry.digitalocean.com/finpro/sentiment-analysis:$(echo $GITHUB_SHA | head -c7)

          echo "Running the new container..."
          docker run -d \
            --restart always \
            --name sentiment-analysis \
            -p 8001:8001 \
            registry.digitalocean.com/finpro/sentiment-analysis:$(echo $GITHUB_SHA | head -c7)

          echo "Deployment complete."
        EOF
      shell: bash

