name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: "registry.digitalocean.com/finpro"
  IMAGE_NAME: "sentiment-analysis"


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker Images
      run: docker-compose build

    - name: Tag Built Image
      run: |
        IMAGE_ID=$(docker images -q <service_name>)
        docker tag $IMAGE_ID $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7}

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600
    
    - name: Remove all old images
      run: if [ ! -z "$(doctl registry repository list | grep "$(echo $IMAGE_NAME)")" ]; then doctl registry repository delete-manifest $(echo $IMAGE_NAME) $(doctl registry repository list-tags $(echo $IMAGE_NAME) | grep -o "sha.*") --force; else echo "No repository"; fi

    - name: Push image to DigitalOcean Container Registry
      run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

    - name: Deploy to DigitalOcean Droplet
      env:
        SSH_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        SSH_USERNAME: ${{ secrets.DIGITALOCEAN_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        echo "Transferring files to remote server..."
        rsync -avz -e "ssh -i private_key.pem" . $SSH_USERNAME@$SSH_HOST:~/sentiment-analysis/

        echo "Deploying application on the server..."
        ssh -i private_key.pem $SSH_USERNAME@$SSH_HOST "
          cd ~/sentiment-analysis &&
          docker-compose pull && # Ensure the latest image is pulled
          docker-compose down &&
          docker-compose up -d
        "

