name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: "registry.digitalocean.com/finpro"
  IMAGE_NAME: "sentiment-analysis"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Set Tag
      run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Create Override for Dynamic Tagging
      run: |
        echo "version: '3.9'
        services:
          api-service:
            image: $REGISTRY/$IMAGE_NAME:$TAG" > docker-compose.override.yaml

    - name: Build Docker Images
      run: docker-compose -f docker-compose.yaml -f docker-compose.override.yaml build

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry
      run: |
        doctl auth init --access-token ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        doctl registry login

    - name: Push Image to DigitalOcean Registry
      run: docker push $REGISTRY/$IMAGE_NAME:$TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Add Remote Host to Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.DIGITALOCEAN_HOST }} >> ~/.ssh/known_hosts
      shell: bash

    - name: Set GitHub SHA Tag
      run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Deploy to DigitalOcean Droplet
      env:
        SSH_HOST: ${{ secrets.DIGITALOCEAN_HOST }}
        SSH_USERNAME: ${{ secrets.DIGITALOCEAN_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      run: |
        set -e

        # Configure SSH
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/private_key.pem
        chmod 600 ~/.ssh/private_key.pem
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

        # Sync application files and model directory to the server
        echo "Transferring files to remote server..."
        rsync -avz -e "ssh -i ~/.ssh/private_key.pem" . $SSH_USERNAME@$SSH_HOST:~/sentiment-analysis/

        # Deploy the application
        echo "Deploying application on the server..."
        ssh -T -i ~/.ssh/private_key.pem $SSH_USERNAME@$SSH_HOST << EOF
          set -e
          set -x
  
          # Export TAG for remote session
          export TAG=$TAG

          # Authenticate Docker with non-interactive login
          echo "Logging into DigitalOcean Container Registry..."
          echo "$DIGITALOCEAN_ACCESS_TOKEN" | docker login registry.digitalocean.com --username $SSH_USERNAME --password-stdin

          # Stop and clean up old container
          echo "Stopping and removing old container..."
          docker stop sentiment-analysis || true
          docker rm sentiment-analysis || true

          # Pull the latest image
          echo "Pulling the latest image..."
          docker pull registry.digitalocean.com/finpro/sentiment-analysis:$TAG

          # Run the new container, mounting the model directory
          echo "Running the new container..."
          docker run -d \
            --restart always \
            --name sentiment-analysis \
            -p 5001:5001 \
            -v /opt/models/finbert_individual2_sentiment_model:/opt/models/finbert_individual2_sentiment_model \
            registry.digitalocean.com/finpro/sentiment-analysis:$TAG

          echo "Deployment complete."
        EOF
      shell: bash
